select SOLICITUDORIGINAL,N_ORDEN_DISTRIBU,SOLICITUD,FECHA_CREACION_ORDEN,ORIGEN,CANCELADO from CUADRATURA_VENTAV_EOM
select SOLICITUDORIGINAL,N_ORDEN_DISTRIBU,SOLICITUD,FECHA_CREACION_ORDEN,ORIGEN,CANCELADO from CUADRATURA_VENTAV_EOM where fecha_creacion_orden >= '12/04/17 00:00:00' and fecha_creacion_orden <= '12/04/17 23:59:59'
select count(*) from CUADRATURA_VENTAV_EOM where fecha_creacion_orden >= '12/04/17 00:00:00' and fecha_creacion_orden <= '12/04/17 23:59:59'
select * from CUADRATURA_VENTAV_EOM

--Total 5819
--12 2057
delete from CUADRATURA_VENTAV_EOM;
delete from CUADRATURA_VENTAV_JDA;

select * from CUADRATURA_VENTAV_JDA;
select PONUMB,POVNUM,NUMDO,POFECE,POHORE,EX14ERROR,EX14FREGi,DESPA from CUADRATURA_VENTAV_JDA;
select PONUMB,POVNUM,NUMDO,POFECE,POHORE,EX14ERROR,EX14FREGi,DESPA from CUADRATURA_VENTAV_JDA WHERE Pofece = '20170412';
select  COUNT(*) from CUADRATURA_VENTAV_JDA WHERE Pofece >= '20170412' AND Pofece <= '20170412';
select COUNT(*) from CUADRATURA_VENTAV_JDA WHERE Pofece = 20170412;

--Total 2691
-- -----------------------------------------------------
-- Table CUADRATURA_VENTA_VERDE_JDA
-- -----------------------------------------------------
CREATE  TABLE  CUADRATURA_VENTAV_JDA (

id INT NOT NULL,
PONUMB VARCHAR(255), 
POVNUM VARCHAR(255), 
NUMDO VARCHAR(255), 
POFECE VARCHAR(255), 
POHORE VARCHAR(255), 
EX14ERROR VARCHAR(255), 
EX14FREGi VARCHAR(255), 
DESPA VARCHAR(255), 
DESPA VARCHAR(255),
PRIMARY KEY (id) 
);


CREATE  INDEX FK_CUADRATURA_VENTAV_PONUMB ON CUADRATURA_VENTAV_JDA(PONUMB ASC);
CREATE  INDEX FK_CUADRATURA_VENTAV_POVNUM ON CUADRATURA_VENTAV_JDA(POVNUM ASC);
CREATE  INDEX FK_CUADRATURA_VENTAV_NUMDO ON CUADRATURA_VENTAV_JDA(NUMDO ASC);
CREATE  INDEX FK_CUADRATURA_VENTAV_POFECE ON CUADRATURA_VENTAV_JDA(POFECE ASC);
CREATE  INDEX FK_CUADRATURA_VENTAV_POHORE ON CUADRATURA_VENTAV_JDA(POHORE ASC);
CREATE  INDEX FK_CUADRATURA_VENTAV_EX14ERROR ON CUADRATURA_VENTAV_JDA(EX14ERROR ASC);
CREATE  INDEX FK_CUADRATURA_VENTAV_EX14FREGi ON CUADRATURA_VENTAV_JDA(EX14FREGi ASC);
CREATE  INDEX FK_CUADRATURA_VENTAV_DESPA ON CUADRATURA_VENTAV_JDA(DESPA ASC);





CREATE SEQUENCE SEQUENCE_CUADRATURA_VENTAV_JDA INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
-- Se encarga de asignar un valor unico y entero en la llave primaria id en la tabla TIMES_LIMIT
CREATE OR REPLACE TRIGGER TRIGGER_CUADRATURA_VENTAV_JDA
BEFORE INSERT ON CUADRATURA_VENTAV_JDA 
FOR EACH ROW
BEGIN
	-- Column "id" INVENTARIO_WMS sequence SEQUENCE_KPI_WEB_CUMPLIMIENTO
	SELECT SEQUENCE_CUADRATURA_VENTAV_JDA.NEXTVAL
	INTO   :new.id
	FROM   dual;
END;

